package calculator;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.lang.String;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author nrack
 */
public class NewJFrame extends javax.swing.JFrame {

    static String textRightNow;
    static int counerDot = 0;
    static double operant1;
    static double operant2;
    static char operation;
    static String str;
    static Border thickBorder = new LineBorder(Color.YELLOW, 2);
    static boolean empty;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plusSign = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        putaSign = new javax.swing.JButton();
        equalSign = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        minusSign = new javax.swing.JButton();
        dotSign = new javax.swing.JButton();
        zeroSign = new javax.swing.JButton();
        deleteSign = new javax.swing.JButton();
        podeljenoSign = new javax.swing.JButton();
        leftZagrada = new javax.swing.JButton();
        rightZagrada = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextField();
        jTextArea2 = new javax.swing.JTextField();
        powSign = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        plusSign.setBackground(new java.awt.Color(255, 102, 0));
        plusSign.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        plusSign.setForeground(new java.awt.Color(255, 255, 255));
        plusSign.setText("+");
        plusSign.setFocusable(false);
        plusSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusSignActionPerformed(evt);
            }
        });

        number3.setBackground(new java.awt.Color(51, 51, 51));
        number3.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number3.setForeground(new java.awt.Color(255, 255, 255));
        number3.setText("3");
        number3.setFocusable(false);
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });

        number1.setBackground(new java.awt.Color(51, 51, 51));
        number1.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number1.setForeground(new java.awt.Color(255, 255, 255));
        number1.setText("1");
        number1.setFocusable(false);
        number1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                number1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                number1MouseReleased(evt);
            }
        });
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number2.setBackground(new java.awt.Color(51, 51, 51));
        number2.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number2.setForeground(new java.awt.Color(255, 255, 255));
        number2.setText("2");
        number2.setFocusable(false);
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });

        number4.setBackground(new java.awt.Color(51, 51, 51));
        number4.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number4.setForeground(new java.awt.Color(255, 255, 255));
        number4.setText("4");
        number4.setFocusable(false);
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });

        number5.setBackground(new java.awt.Color(51, 51, 51));
        number5.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number5.setForeground(new java.awt.Color(255, 255, 255));
        number5.setText("5");
        number5.setFocusable(false);
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });

        number6.setBackground(new java.awt.Color(51, 51, 51));
        number6.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number6.setForeground(new java.awt.Color(255, 255, 255));
        number6.setText("6");
        number6.setFocusable(false);
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });

        putaSign.setBackground(new java.awt.Color(255, 102, 0));
        putaSign.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        putaSign.setForeground(new java.awt.Color(255, 255, 255));
        putaSign.setText("*");
        putaSign.setFocusable(false);
        putaSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putaSignActionPerformed(evt);
            }
        });

        equalSign.setBackground(new java.awt.Color(255, 102, 0));
        equalSign.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        equalSign.setForeground(new java.awt.Color(255, 255, 255));
        equalSign.setText("=");
        equalSign.setFocusable(false);
        equalSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalSignActionPerformed(evt);
            }
        });

        number7.setBackground(new java.awt.Color(51, 51, 51));
        number7.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number7.setForeground(new java.awt.Color(255, 255, 255));
        number7.setText("7");
        number7.setFocusable(false);
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        number8.setBackground(new java.awt.Color(51, 51, 51));
        number8.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number8.setForeground(new java.awt.Color(255, 255, 255));
        number8.setText("8");
        number8.setFocusable(false);
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        number9.setBackground(new java.awt.Color(51, 51, 51));
        number9.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        number9.setForeground(new java.awt.Color(255, 255, 255));
        number9.setText("9");
        number9.setFocusable(false);
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });

        minusSign.setBackground(new java.awt.Color(255, 102, 0));
        minusSign.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        minusSign.setForeground(new java.awt.Color(255, 255, 255));
        minusSign.setText("-");
        minusSign.setFocusable(false);
        minusSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusSignActionPerformed(evt);
            }
        });

        dotSign.setBackground(new java.awt.Color(51, 51, 51));
        dotSign.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        dotSign.setForeground(new java.awt.Color(255, 255, 255));
        dotSign.setText(".");
        dotSign.setFocusable(false);
        dotSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotSignActionPerformed(evt);
            }
        });

        zeroSign.setBackground(new java.awt.Color(51, 51, 51));
        zeroSign.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        zeroSign.setForeground(new java.awt.Color(255, 255, 255));
        zeroSign.setText("0");
        zeroSign.setFocusable(false);
        zeroSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroSignActionPerformed(evt);
            }
        });

        deleteSign.setBackground(new java.awt.Color(51, 51, 51));
        deleteSign.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        deleteSign.setForeground(new java.awt.Color(255, 255, 255));
        deleteSign.setText("CE");
        deleteSign.setFocusable(false);
        deleteSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSignActionPerformed(evt);
            }
        });

        podeljenoSign.setBackground(new java.awt.Color(255, 102, 0));
        podeljenoSign.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        podeljenoSign.setForeground(new java.awt.Color(255, 255, 255));
        podeljenoSign.setText("/");
        podeljenoSign.setFocusable(false);
        podeljenoSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                podeljenoSignActionPerformed(evt);
            }
        });

        leftZagrada.setBackground(new java.awt.Color(51, 51, 51));
        leftZagrada.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        leftZagrada.setForeground(new java.awt.Color(255, 255, 255));
        leftZagrada.setText("C");
        leftZagrada.setFocusable(false);
        leftZagrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftZagradaActionPerformed(evt);
            }
        });

        rightZagrada.setBackground(new java.awt.Color(51, 51, 51));
        rightZagrada.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        rightZagrada.setForeground(new java.awt.Color(255, 255, 255));
        rightZagrada.setText("√ ");
        rightZagrada.setFocusable(false);
        rightZagrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightZagradaActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setFont(new java.awt.Font("Open Sans", 1, 32)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 102, 0));
        jTextArea1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextArea1.setBorder(null);
        jTextArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextArea1ActionPerformed(evt);
            }
        });

        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setFont(new java.awt.Font("Open Sans", 1, 28)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 102, 0));
        jTextArea2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextArea2.setBorder(null);
        jTextArea2.setFocusable(false);
        jTextArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextArea2ActionPerformed(evt);
            }
        });

        powSign.setBackground(new java.awt.Color(51, 51, 51));
        powSign.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        powSign.setForeground(new java.awt.Color(255, 255, 255));
        powSign.setText("P");
        powSign.setFocusable(false);
        powSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powSignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(putaSign, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dotSign, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(zeroSign, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(leftZagrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rightZagrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(powSign, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(equalSign, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(deleteSign, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(podeljenoSign, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minusSign, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextArea1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plusSign, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextArea2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusSign, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusSign, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(putaSign, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dotSign, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zeroSign, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSign, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(podeljenoSign, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftZagrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightZagrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powSign, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalSign, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        textRightNow = jTextArea1.getText();

        jTextArea1.setText(textRightNow + "1");

    }//GEN-LAST:event_number1ActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "2");
    }//GEN-LAST:event_number2ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "4");
    }//GEN-LAST:event_number4ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "5");
    }//GEN-LAST:event_number5ActionPerformed

    private void equalSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalSignActionPerformed
        if (jTextArea1.getText().equals(null) || jTextArea1.getText().equals("")) {
            return;
        }
        counerDot = 0;
        operant2 = Double.parseDouble(jTextArea1.getText());
        String sum = String.valueOf(calc());
        jTextArea1.setText(sum);
        jTextArea2.setText("");
    }//GEN-LAST:event_equalSignActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "7");
    }//GEN-LAST:event_number7ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "8");
    }//GEN-LAST:event_number8ActionPerformed

    private void dotSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotSignActionPerformed
        if (counerDot > 0) {
            return;
        }
        if (jTextArea1.getText().equals("")) {
            jTextArea1.setText("0.");
        } else {
            textRightNow = jTextArea1.getText();
            jTextArea1.setText(textRightNow + ".");
            counerDot++;

        }

    }//GEN-LAST:event_dotSignActionPerformed

    private void zeroSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroSignActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "0");
    }//GEN-LAST:event_zeroSignActionPerformed

    private void leftZagradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftZagradaActionPerformed

        str = jTextArea1.getText();
        if (str.equals(null) || str.equals("")) {
            return;
        }
        jTextArea1.setText(removeLastChar(str));

    }//GEN-LAST:event_leftZagradaActionPerformed
    private static String removeLastChar(String str) {
        return str.substring(0, str.length() - 1);
    }
    private void rightZagradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightZagradaActionPerformed
        if (jTextArea1.getText().equals(null) || jTextArea1.getText().equals("")) {
            return;
        }
        double square = Double.parseDouble(jTextArea1.getText());
        square = Math.sqrt(square);
        jTextArea1.setText(String.valueOf(square));
    }//GEN-LAST:event_rightZagradaActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "3");
    }//GEN-LAST:event_number3ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "6");
    }//GEN-LAST:event_number6ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        textRightNow = jTextArea1.getText();
        jTextArea1.setText(textRightNow + "9");
    }//GEN-LAST:event_number9ActionPerformed

    private void deleteSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSignActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_deleteSignActionPerformed

    private void plusSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusSignActionPerformed
        if (jTextArea1.getText().equals(null) || jTextArea1.getText().equals("")) {
            return;
        }
        operation = '+';
        counerDot = 0;
        try {
            operant1 = Double.parseDouble(jTextArea1.getText());

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Wrong input", null, JOptionPane.ERROR_MESSAGE);
        }
        jTextArea2.setText(jTextArea1.getText() + " +");
        jTextArea1.setText("");

    }//GEN-LAST:event_plusSignActionPerformed

    private void minusSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusSignActionPerformed
        if (jTextArea1.getText().equals(null) || jTextArea1.getText().equals("")) {
            return;
        }
        operation = '-';
        counerDot = 0;
        try {
            operant1 = Double.parseDouble(jTextArea1.getText());

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Wrong input", null, JOptionPane.ERROR_MESSAGE);
        }
        jTextArea2.setText(jTextArea1.getText() + " -");
        jTextArea1.setText("");
    }//GEN-LAST:event_minusSignActionPerformed

    private void putaSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putaSignActionPerformed
        if (jTextArea1.getText().equals(null) || jTextArea1.getText().equals("")) {
            return;
        }
        operation = '*';
        counerDot = 0;
        try {
            operant1 = Double.parseDouble(jTextArea1.getText());

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Wrong input", null, JOptionPane.ERROR_MESSAGE);
        }
        jTextArea2.setText(jTextArea1.getText() + " *");
        jTextArea1.setText("");
    }//GEN-LAST:event_putaSignActionPerformed

    private void podeljenoSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_podeljenoSignActionPerformed
        if (jTextArea1.getText().equals(null) || jTextArea1.getText().equals("")) {
            return;
        }
        operation = '/';
        counerDot = 0;
        try {
            operant1 = Double.parseDouble(jTextArea1.getText());

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Wrong input", null, JOptionPane.ERROR_MESSAGE);
        }
        jTextArea2.setText(jTextArea1.getText() + " /");
        jTextArea1.setText("");
    }//GEN-LAST:event_podeljenoSignActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void number1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number1MousePressed

    }//GEN-LAST:event_number1MousePressed

    private void number1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number1MouseReleased

    }//GEN-LAST:event_number1MouseReleased

    private void jTextArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextArea1ActionPerformed

    }//GEN-LAST:event_jTextArea1ActionPerformed

    private void jTextArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextArea2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea2ActionPerformed

    private void powSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powSignActionPerformed
        if (jTextArea1.getText().equals("")) {
            return;
        }
        double res = Double.parseDouble(jTextArea1.getText());
        res = Math.pow(res, 2);
        jTextArea1.setText(String.valueOf(res));
    }//GEN-LAST:event_powSignActionPerformed
    private double calc() {
        double res = 0;
        switch (operation) {
            case '+':
                res = operant1 + operant2;
                break;
            case '-':
                res = operant1 - operant2;
                break;
            case '*':
                res = operant1 * operant2;
                break;
            case '/':
                jTextArea1.setText("Deljenje sa nulom nije dozvoljeno");
                res = operant1 / operant2;
                break;
        }
        return res;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteSign;
    private javax.swing.JButton dotSign;
    private javax.swing.JButton equalSign;
    private javax.swing.JTextField jTextArea1;
    private javax.swing.JTextField jTextArea2;
    private javax.swing.JButton leftZagrada;
    private javax.swing.JButton minusSign;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JButton plusSign;
    private javax.swing.JButton podeljenoSign;
    private javax.swing.JButton powSign;
    private javax.swing.JButton putaSign;
    private javax.swing.JButton rightZagrada;
    private javax.swing.JButton zeroSign;
    // End of variables declaration//GEN-END:variables
}
